In [2]:
#Import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Filepath
filepath = '/Users/epalmer/MET4400C_Ins-obs_labs/Labs/lab_3_files/Data_Lab3'

# Important Constants
Rd = 287 # Specific gas constant of dry air
Rv = 461.5 # Specific gas constant of moist air/ water vapor
eps = Rv/Rd # Saturated vapor pressure
Lv = 2.5*10**6 # latent heat of vaporization
cp = 1004 # specific heat of air at constant pressure
C = 1.2 * 10**-3 # Bulk transfer coefficient

In [4]:
# Reading in the Lake Ella Data
data = pd.read_csv(f'{filepath}/Lake_Ella_Data_Collection.csv', header=1)
data

,t,p,Tair1,Tair2,Tair3,Tair4,Tair5,Tair6,Tw1,Tw2,...,Tw5,Tw6,Tsfc1,Tsfc2,U1,U2,U3,U4,U5,U6
0,3/6/2026 11:30 AM,1022.8,25.0,25.5,24.0,25.0,25,24.0,22.0,22.0,...,22,22.0,21.9,24.3,1.3,1.9,1.1,0.4,0.8,1.9
1,3/6/2026 11:33 AM,1022.8,25.0,25.0,25.0,25.5,26,24.0,21.0,21.0,...,22,21.4,21.5,23.5,0.5,2.9,0.6,0.5,1.3,0.5
2,3/6/2026 11:36 AM,1022.8,25.0,24.5,25.0,25.0,25,24.5,21.0,21.0,...,21,22.0,21.5,23.4,1.3,0.6,0.5,0.6,0.0,1.0
3,3/6/2026 11:39 AM,1022.7,25.2,25.0,25.0,25.0,25,24.5,21.0,21.0,...,21,21.2,21.9,23.5,0.9,2.3,1.5,0.4,0.0,1.8
4,3/6/2026 11:42 AM,1022.7,25.0,24.5,25.0,25.0,25,25.0,21.0,21.0,...,21,22.0,22.1,23.6,0.7,1.0,0.6,0.6,0.5,2.0
5,3/6/2026 11:45 AM,1022.7,25.5,25.5,25.0,25.5,25,25.1,21.5,21.5,...,22,22.0,23.0,23.5,0.8,0.9,0.7,0.7,0.7,1.4
6,3/6/2026 11:48 AM,1022.7,25.8,25.0,25.5,25.0,25,24.5,21.0,21.0,...,22,21.9,22.5,23.5,0.4,3.0,0.4,0.4,1.0,1.3
7,3/6/2026 11:51 AM,1022.7,25.5,26.0,26.0,25.5,26,25.0,21.5,21.5,...,22,22.0,21.8,23.3,1.4,0.6,0.6,0.9,0.8,1.4
8,3/6/2026 11:54 AM,1022.6,26.0,24.5,26.0,25.5,26,25.0,21.0,21.0,...,22,22.0,22.4,24.0,1.2,0.6,0.8,0.3,0.6,1.2
9,3/6/2026 11:57 AM,1022.6,26.0,26.0,26.0,26.0,26,25.0,22.5,22.5,...,23,22.0,21.7,25.5,0.0,0.7,0.8,1.2,0.4,0.4
10,3/6/2026 12:00 PM,1022.6,26.1,27.5,26.0,26.0,26,26.5,23.0,23.0,...,23,22.0,21.0,26.0,0.7,0.5,1.0,1.4,0.7,0.6
11,3/6/2026 12:03 PM,1022.6,25.7,25.0,26.0,26.0,27,25.0,21.0,21.0,...,24,22.1,21.3,20.0,1.5,4.3,0.8,0.3,0.5,1.5
12,3/6/2026 12:06 PM,1022.6,25.4,25.5,26.2,26.0,26,25.0,21.0,21.0,...,22,21.9,21.4,23.3,1.3,1.4,0.4,1.0,0.9,0.9
13,3/6/2026 12:09 PM,1022.5,26.0,25.5,26.0,26.0,26,25.9,20.5,20.5,...,22,22.0,21.3,23.3,0.0,1.9,0.4,1.9,0.0,1.4
14,3/6/2026 12:12 PM,1022.5,25.9,25.5,25.0,25.5,26,25.0,20.5,20.5,...,22,22.0,21.6,24.0,2.2,0.5,1.2,0.3,0.8,0.4
15,3/6/2026 12:15 PM,1022.5,25.6,25.0,25.0,25.5,26,25.1,21.0,21.0,...,22,22.2,21.8,23.0,1.4,1.0,0.4,0.0,1.2,0.5
16,3/6/2026 12:18 PM,1022.5,25.1,24.5,26.0,24.0,26,25.0,23.5,23.5,...,22,22.0,21.5,23.1,1.5,2.2,0.0,1.4,0.3,2.2
17,3/6/2026 12:21 PM,1022.5,25.6,26.0,26.0,26.0,26,26.0,21.0,21.0,...,22,23.0,22.1,23.0,0.7,1.3,1.2,0.4,0.0,0.8
18,3/6/2026 12:24 PM,1022.4,26.0,25.5,26.0,26.5,27,25.0,21.5,21.5,...,22,22.2,21.5,24.4,0.8,2.1,0.4,0.5,0.6,3.3
19,3/6/2026 12:27 PM,1022.4,25.8,26.0,26.0,25.5,26,25.0,21.5,21.5,...,22,22.5,22.2,24.9,2.6,0.4,0.6,1.7,0.0,0.4
20,3/6/2026 12:30 PM,1022.4,25.9,25.0,25.7,26.0,26,24.9,21.0,21.0,...,22,22.0,21.7,25.0,1.5,1.4,1.4,1.0,0.6,0.8

In [5]:
# Get pressure from datafram
p = data['p'] * 10**2 # convert from hPa to Pa
p

0     102280.0
1     102280.0
2     102280.0
3     102270.0
4     102270.0
5     102270.0
6     102270.0
7     102270.0
8     102260.0
9     102260.0
10    102260.0
11    102260.0
12    102260.0
13    102250.0
14    102250.0
15    102250.0
16    102250.0
17    102250.0
18    102240.0
19    102240.0
20    102240.0
Name: p, dtype: float64

In [6]:
# Get dry bulb temperature data
Tair_cols = [f'Tair{n}' for n in range(1,6+1)] # selecting all the columns of dry bulb measurements
Tair = data[Tair_cols].mean(axis = 1) + 273.15 # Average Temperature of all air measurements in Kelvin
Tair

0     297.900000
1     298.233333
2     297.983333
3     298.100000
4     298.066667
5     298.416667
6     298.283333
7     298.816667
8     298.650000
9     298.983333
10    299.500000
11    298.933333
12    298.833333
13    299.050000
14    298.633333
15    298.516667
16    298.250000
17    299.083333
18    299.150000
19    298.866667
20    298.733333
dtype: float64

In [7]:
# Get Wet bulb temperature 
Twet_cols = [f'Tw{n}' for n in range(1,6+1)] # Selecting all the columns of wet bulb measurements
Twet = data[Twet_cols].mean(axis=1) + 273.15 # Average Temperature of all wet bulb air measurements in kelvin
Twet

0     295.066667
1     294.633333
2     294.816667
3     294.683333
4     294.816667
5     295.150000
6     295.050000
7     295.233333
8     295.100000
9     295.983333
10    296.150000
11    295.500000
12    295.133333
13    295.066667
14    294.900000
15    295.100000
16    295.983333
17    295.316667
18    295.266667
19    295.400000
20    295.150000
dtype: float64

In [8]:
#Get wind speed data in m s-1
U_cols = [f'U{n}' for n in range(1,6+1)]
U = data[U_cols] #Don't average yet, as we care about the standard deviation of all the wind measurements
U

     U1   U2   U3   U4   U5   U6
0   1.3  1.9  1.1  0.4  0.8  1.9
1   0.5  2.9  0.6  0.5  1.3  0.5
2   1.3  0.6  0.5  0.6  0.0  1.0
3   0.9  2.3  1.5  0.4  0.0  1.8
4   0.7  1.0  0.6  0.6  0.5  2.0
5   0.8  0.9  0.7  0.7  0.7  1.4
6   0.4  3.0  0.4  0.4  1.0  1.3
7   1.4  0.6  0.6  0.9  0.8  1.4
8   1.2  0.6  0.8  0.3  0.6  1.2
9   0.0  0.7  0.8  1.2  0.4  0.4
10  0.7  0.5  1.0  1.4  0.7  0.6
11  1.5  4.3  0.8  0.3  0.5  1.5
12  1.3  1.4  0.4  1.0  0.9  0.9
13  0.0  1.9  0.4  1.9  0.0  1.4
14  2.2  0.5  1.2  0.3  0.8  0.4
15  1.4  1.0  0.4  0.0  1.2  0.5
16  1.5  2.2  0.0  1.4  0.3  2.2
17  0.7  1.3  1.2  0.4  0.0  0.8
18  0.8  2.1  0.4  0.5  0.6  3.3
19  2.6  0.4  0.6  1.7  0.0  0.4
20  1.5  1.4  1.4  1.0  0.6  0.8

In [9]:
# Calculating Saturation Vapor Pressure es(T) using the Clausius-Clapeyron equation
def es(T):
    '''Calculate the Saturation Vapor Pressure using the Clausius-Clapeyron equation
    
    Parameters 
    ----------
    T : K 
    Temperature in Kelvin
    
    Returns
    ----------
    es : Pa 
    Saturation Vapor Pressure in Pascals
    '''
    #Formula es(T) = Aw * exp(-Bw/T)
    Aw = 2.53 * 10**11 # Pa
    Bw = 5420 # K
    es = Aw * np.exp(-Bw/T)

    return es

In [10]:
# calculating Saturation vapor pressure using function
esw = es(Twet) # Saturation vapor pressure at wet bulb temperature
esw

0     2664.908748
1     2593.877659
2     2623.720675
3     2601.986509
4     2623.720675
5     2678.765586
6     2662.145058
7     2692.686591
8     2670.443799
9     2820.906152
10    2850.127309
11    2737.668037
12    2675.989093
13    2664.908748
14    2637.386549
15    2670.443799
16    2820.906152
17    2706.672024
18    2698.273018
19    2720.722142
20    2678.765586
dtype: float64

In [ ]:
# Partial Pressure of water vapor
A =